package tmux

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donjor/zmux/internal/config"
	"github.com/donjor/zmux/internal/theme"
)

// GenerateConf produces a tmux configuration string from the given config and palette.
// zmuxBin is the path to the zmux binary for run-shell commands.
func GenerateConf(cfg *config.Config, palette *theme.Palette, zmuxBin string) string {
	var b strings.Builder

	// Header
	b.WriteString("# Generated by zmux — do not edit manually\n")
	b.WriteString("# https://github.com/donjor/zmux\n\n")

	// General settings
	writeSection(&b, "General")
	b.WriteString("set -g default-terminal \"xterm-256color\"\n")
	b.WriteString("set -ga terminal-overrides \",xterm-256color:Tc\"\n")
	b.WriteString("set -g extended-keys on\n")
	b.WriteString("set -ga terminal-features \",xterm-256color:extkeys\"\n")
	b.WriteString("set -g mouse on\n")
	b.WriteString("set -g history-limit 50000\n")
	b.WriteString("set -g escape-time 10\n")
	b.WriteString("set -g focus-events on\n")
	b.WriteString("set -g base-index 1\n")
	b.WriteString("setw -g pane-base-index 1\n")
	b.WriteString("set -g renumber-windows on\n")
	b.WriteString("set -g set-clipboard on\n")
	b.WriteString("set -g status-position top\n")
	b.WriteString("set -g status-interval 5\n")
	b.WriteString("set -g status-left-length 40\n")
	b.WriteString("set -g status-right-length 100\n")
	b.WriteString("\n")

	// Prefix
	prefix := cfg.Prefix
	if prefix == "" {
		prefix = "C-Space"
	}
	writeSection(&b, "Prefix")
	b.WriteString("unbind C-b\n")
	fmt.Fprintf(&b, "set -g prefix %s\n", prefix)
	fmt.Fprintf(&b, "bind %s send-prefix\n", prefix)
	b.WriteString("\n")

	// Vim copy mode
	writeSection(&b, "Vim copy mode")
	b.WriteString("setw -g mode-keys vi\n")
	b.WriteString("\n")
	b.WriteString("bind v copy-mode\n")
	b.WriteString("bind -T copy-mode-vi v send -X begin-selection\n")
	b.WriteString("bind -T copy-mode-vi Escape send -X cancel\n")
	b.WriteString("bind -T copy-mode-vi C-v send -X rectangle-toggle\n")
	b.WriteString("bind -T copy-mode-vi / command-prompt -p \"search down:\" \"send -X search-forward '%%'\"\n")
	b.WriteString("bind -T copy-mode-vi ? command-prompt -p \"search up:\" \"send -X search-backward '%%'\"\n")
	b.WriteString("\n")

	// Clipboard
	clipTool := DetectClipboard()
	b.WriteString("# Clipboard\n")
	b.WriteString(ClipboardBinding(clipTool))
	b.WriteString("\n\n")

	// Windows (tabs)
	writeSection(&b, "Windows")
	b.WriteString("bind c new-window -c \"#{pane_current_path}\"\n")
	b.WriteString("bind n next-window\n")
	b.WriteString("bind . command-prompt -p \"rename tab:\" \"rename-window '%%'\"\n")
	b.WriteString("\n")

	// Alt+1-5 tab switching
	b.WriteString("# Alt+1-5 tab switching (no prefix)\n")
	for i := 1; i <= 5; i++ {
		fmt.Fprintf(&b, "bind -n M-%d select-window -t %d\n", i, i)
	}
	b.WriteString("\n")

	// Sessions
	writeSection(&b, "Sessions")
	b.WriteString("bind , command-prompt -p \"rename session:\" \"rename-session '%%'\"\n")
	b.WriteString("bind s choose-tree -s\n")
	b.WriteString("bind x confirm-before -p \"kill session #S? (y/n)\" \"run-shell 'tmux kill-session -t \\\"#S\\\"'\"\n")
	b.WriteString("\n")

	// Pasting
	writeSection(&b, "Pasting")
	b.WriteString("bind p paste-buffer\n")
	b.WriteString("\n")

	// Popup binding (prefix+d)
	writeSection(&b, "Popup")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind d display-popup -w 80%% -h 80%% -E \"%s --dashboard\"\n", zmuxBin)
	} else {
		b.WriteString("bind d display-popup -w 80% -h 80% -E \"zmux --dashboard\"\n")
	}
	b.WriteString("\n")

	// Help popup (prefix+?)
	b.WriteString("# Help\n")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind ? display-popup -w 60%% -h 60%% -E \"%s help\"\n", zmuxBin)
	}
	b.WriteString("\n")

	// Reload
	writeSection(&b, "Reload")
	b.WriteString("bind r source-file ~/.tmux.conf \\; display \"Config reloaded\"\n")
	b.WriteString("\n")

	// Bootstrap: run-shell for zmux apply
	writeSection(&b, "Bootstrap")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "run-shell \"%s apply\"\n", zmuxBin)
	}

	return b.String()
}

// WriteConf writes the generated config content to the given path,
// creating parent directories as needed.
func WriteConf(fs config.FS, path, content string) error {
	dir := filepath.Dir(path)
	if err := fs.MkdirAll(dir, os.FileMode(0o755)); err != nil {
		return fmt.Errorf("create config dir %q: %w", dir, err)
	}
	if err := fs.WriteFile(path, []byte(content), os.FileMode(0o644)); err != nil {
		return fmt.Errorf("write config %q: %w", path, err)
	}
	return nil
}

func writeSection(b *strings.Builder, name string) {
	fmt.Fprintf(b, "# --- %s ---\n", name)
}
