package tmux

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donjor/zmux/internal/config"
	"github.com/donjor/zmux/internal/keys"
	"github.com/donjor/zmux/internal/tablabel"
	"github.com/donjor/zmux/internal/termtitle"
	"github.com/donjor/zmux/internal/theme"
)

// GenerateConf produces a tmux configuration string from the given config and palette.
// zmuxBin is the path to the zmux binary for run-shell commands.
func GenerateConf(cfg *config.Config, palette *theme.Palette, zmuxBin string) string {
	var b strings.Builder

	// Header
	b.WriteString("# Generated by zmux — do not edit manually\n")
	b.WriteString("# https://github.com/donjor/zmux\n\n")

	// General settings
	writeSection(&b, "General")
	b.WriteString("set -g default-terminal \"tmux-256color\"\n")
	b.WriteString("set -g extended-keys on\n")
	b.WriteString("# zmux owns terminal-features[90..99] to keep repeated apply idempotent.\n")
	b.WriteString("set -g terminal-features[90] \"xterm-256color:RGB:extkeys\"\n")
	b.WriteString("set -g terminal-features[91] \"xterm-ghostty:RGB:extkeys\"\n")
	b.WriteString("set -g terminal-features[92] \"tmux-256color:RGB:extkeys\"\n")
	b.WriteString("set -g mouse on\n")
	b.WriteString("set -g history-limit 50000\n")
	b.WriteString("set -g escape-time 10\n")
	b.WriteString("set -g focus-events on\n")
	b.WriteString("set -g base-index 1\n")
	b.WriteString("setw -g pane-base-index 1\n")
	b.WriteString("set -g renumber-windows on\n")
	// Use tmux's normal command-based auto naming. zmux marks duplicate names
	// separately so the status bar can add a cwd suffix only when needed.
	b.WriteString("setw -g automatic-rename on\n")
	b.WriteString("setw -g automatic-rename-format \"#{?pane_in_mode,[tmux],#{pane_current_command}}\"\n")
	// Keep the tab visible when its last foreground command exits by failure or
	// signal (for example Ctrl+C spam killing a full-tab Pi session). Clean status
	// 0 exits close normally instead of leaving a confusing dead pane.
	b.WriteString("setw -g remain-on-exit failed\n")
	b.WriteString("setw -g remain-on-exit-format \"Pane stopped unexpectedly#{?#{!=:#{pane_dead_status},}, (status #{pane_dead_status}),}#{?#{!=:#{pane_dead_signal},}, (signal #{pane_dead_signal}),} — press prefix+x to close the tab\"\n")
	b.WriteString("set -g set-clipboard on\n")
	b.WriteString("set -g status-position top\n")
	b.WriteString("set -g set-titles on\n")
	fmt.Fprintf(&b, "set -g set-titles-string \"%s\"\n", termtitle.TmuxTitleFormat)
	b.WriteString("set -g status-interval 5\n")
	b.WriteString("set -g status-left-length 40\n")
	b.WriteString("set -g status-right-length 100\n")
	b.WriteString("\n")

	// Prefix
	prefix := cfg.Prefix
	if prefix == "" {
		prefix = "C-Space"
	}
	writeSection(&b, "Prefix")
	b.WriteString("unbind C-b\n")
	fmt.Fprintf(&b, "set -g prefix %s\n", prefix)
	fmt.Fprintf(&b, "bind %s send-prefix\n", prefix)
	b.WriteString("\n")

	// Vim copy mode
	writeSection(&b, "Vim copy mode")
	b.WriteString("setw -g mode-keys vi\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "bind %s copy-mode\n", keys.CopyModeKey.Key)
	fmt.Fprintf(&b, "bind %s respawn-pane -k\n", keys.PaneRespawn.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X begin-selection\n", keys.CopyBeginSelection.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X cancel\n", keys.CopyCancel.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X rectangle-toggle\n", keys.CopyRectangle.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s command-prompt -p \"search down:\" \"send -X search-forward '%%%%'\"\n", keys.CopySearchForward.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s command-prompt -p \"search up:\" \"send -X search-backward '%%%%'\"\n", keys.CopySearchBackward.Key)
	b.WriteString("\n")

	// Clipboard
	clipTool := DetectClipboard()
	b.WriteString("# Clipboard\n")
	b.WriteString(ClipboardBinding(clipTool))
	b.WriteString("\n\n")

	// Windows (tabs)
	writeSection(&b, "Windows")
	fmt.Fprintf(&b, "bind %s new-window -c \"#{pane_current_path}\"\n", keys.NewTab.Key)
	fmt.Fprintf(&b, "bind %s next-window\n", keys.TabNext.Key)
	fmt.Fprintf(&b, "bind %s previous-window\n", keys.TabPrev.Key)
	fmt.Fprintf(&b, "bind %s command-prompt -p \"label tab (blank clears):\" \"set-option -w -t #{window_id} @zmux_label '%%%%' \\; set-option -w -t #{window_id} @zmux_label_source manual\"\n", keys.LabelTab.Key)
	fmt.Fprintf(&b, "bind %s swap-window -t -1 \\; select-window -t -1\n", keys.TabReorderLeft.Key)
	fmt.Fprintf(&b, "bind %s swap-window -t +1 \\; select-window -t +1\n", keys.TabReorderRight.Key)
	fmt.Fprintf(&b, "bind %s confirm-before -p \"close tab %s? (y/n)\" kill-window\n", keys.TabKill.Key, tablabel.PlainFormat())
	b.WriteString("\n")

	// Alt+1-9 tab switching (no prefix)
	b.WriteString("# Alt+1-9 tab switching (no prefix)\n")
	for i := 1; i <= 9; i++ {
		fmt.Fprintf(&b, "bind -n M-%d select-window -t %d\n", i, i)
	}
	b.WriteString("\n")

	// Alt+` tab switcher for current session (no prefix)
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind -n %s display-popup -w 60%% -h 40%% -E \"%s --tab-picker\"\n", keys.TabSwitch.Key, zmuxBin)
	}
	b.WriteString("\n")

	// No-prefix pane focus. Ghostty and Hyprland leave Alt+Shift+Arrow free,
	// making this a fast path for Pi ↔ sidecar movement without stealing
	// Neovim's Ctrl+h/j/k/l window navigation.
	b.WriteString("# Alt+Shift+Arrow pane focus (no prefix)\n")
	fmt.Fprintf(&b, "bind -n %s select-pane -L\n", keys.PaneFocusL.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -R\n", keys.PaneFocusR.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -U\n", keys.PaneFocusU.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -D\n", keys.PaneFocusD.Key)
	b.WriteString("\n")

	// Sessions
	writeSection(&b, "Sessions")
	fmt.Fprintf(&b, "bind %s command-prompt -p \"rename session:\" \"rename-session '%%%%'\"\n", keys.RenameSession.Key)
	if zmuxBin != "" {
		// prefix+C (shift-c): create new session in current workspace.
		fmt.Fprintf(&b, "bind %s command-prompt -p \"new session:\" \"run-shell '%s workspace new-session %%%%'\"\n", keys.NewSession.Key, zmuxBin)
	}
	b.WriteString("\n")

	// Session navigation (workspace-scoped)
	writeSection(&b, "Session navigation")
	if zmuxBin != "" {
		// prefix+w / prefix+s: workspace+session picker. Both keys open
		// the same picker — aliases that match user muscle memory
		// (w = workspace, s = session). The picker is hierarchical so
		// either entry point works.
		for _, k := range append([]string{keys.SessionPicker.Key}, keys.SessionPicker.Aliases...) {
			fmt.Fprintf(&b, "bind %s display-popup -w 60%% -h 50%% -E \"%s --picker\"\n", k, zmuxBin)
		}
		// prefix+[ / prefix+]: cycle prev/next session in workspace
		fmt.Fprintf(&b, "bind %s run-shell \"%s workspace prev\"\n", keys.SessionPrev.Key, zmuxBin)
		fmt.Fprintf(&b, "bind %s run-shell \"%s workspace next\"\n", keys.SessionNext.Key, zmuxBin)
		// Shift+Alt+1-9: direct session switching within workspace
		for i := 1; i <= 9; i++ {
			fmt.Fprintf(&b, "bind -n M-S-%d run-shell \"%s workspace switch-to %d\"\n", i, zmuxBin, i)
		}
	} else {
		b.WriteString("bind s choose-tree -s\n")
	}
	b.WriteString("\n")

	// Pasting
	writeSection(&b, "Pasting")
	fmt.Fprintf(&b, "bind %s paste-buffer\n", keys.Paste.Key)
	b.WriteString("\n")

	// Command Palette popup (prefix+p)
	writeSection(&b, "Command Palette")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s display-popup -w 60%% -h 50%% -E \"%s --palette\"\n", keys.Palette.Key, zmuxBin)
	} else {
		fmt.Fprintf(&b, "bind %s display-popup -w 60%% -h 50%% -E \"zmux --palette\"\n", keys.Palette.Key)
	}
	b.WriteString("\n")

	// Dashboard popup (prefix+Space — "double-tap" zmux)
	writeSection(&b, "Dashboard")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s display-popup -w 80%% -h 80%% -E \"%s --dashboard\"\n", keys.Dashboard.Key, zmuxBin)
	} else {
		fmt.Fprintf(&b, "bind %s display-popup -w 80%% -h 80%% -E \"zmux --dashboard\"\n", keys.Dashboard.Key)
	}
	b.WriteString("\n")

	// Help popup (prefix+?)
	b.WriteString("# Help\n")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s display-popup -w 60%% -h 60%% -E \"%s help\"\n", keys.Help.Key, zmuxBin)
	}
	b.WriteString("\n")

	// Scratch shell popup (prefix+!) — throwaway $SHELL in a popup, cwd
	// inherits from the calling pane, closes on exit.
	writeSection(&b, "Scratch shell")
	fmt.Fprintf(&b, "bind %s display-popup -E -w 80%% -h 70%% -T \" scratch shell \" -d \"#{pane_current_path}\" \"$SHELL\"\n", keys.ScratchShell.Key)
	b.WriteString("\n")

	// Reload (prefix+r runs full zmux apply — regenerates conf + applies everything)
	writeSection(&b, "Reload")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s run-shell \"%s apply\" \\; display \"zmux reloaded\"\n", keys.Reload.Key, zmuxBin)
	} else {
		fmt.Fprintf(&b, "bind %s source-file ~/.tmux.conf \\; display \"Config reloaded\"\n", keys.Reload.Key)
	}
	b.WriteString("\n")

	// Status bar refresh hooks — force immediate refresh on context change
	// so the bar doesn't show stale session/window info for 5 seconds.
	writeSection(&b, "Status refresh hooks")
	b.WriteString("set-hook -g client-session-changed \"refresh-client -S\"\n")
	b.WriteString("set-hook -g session-window-changed \"refresh-client -S\"\n")
	b.WriteString("set-hook -g window-linked \"refresh-client -S\"\n")
	b.WriteString("set-hook -g window-renamed \"refresh-client -S\"\n")
	b.WriteString("set-hook -g session-renamed \"refresh-client -S\"\n")
	if zmuxBin != "" {
		// Clear older generated hook slots before installing the current silent,
		// best-effort hooks. In particular, a legacy unindexed window-unlinked hook
		// could surface noisy "returned 1" messages from old binaries.
		b.WriteString("set-hook -gu window-unlinked[0]\n")
		b.WriteString("set-hook -gu window-linked[1]\n")
		b.WriteString("set-hook -gu window-unlinked[1]\n")
		b.WriteString("set-hook -gu window-renamed[1]\n")
		refreshNamesCmd := fmt.Sprintf("%s tab refresh-names #{session_name} >/dev/null 2>&1 || true", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g window-linked[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
		fmt.Fprintf(&b, "set-hook -g window-unlinked[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
		fmt.Fprintf(&b, "set-hook -g window-renamed[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
	}

	// Two-line bar hooks — adjust status line count when sessions appear/disappear.
	// No -b flag: run synchronously so the status count is correct before redraw.
	if zmuxBin != "" {
		fmt.Fprintf(&b, "set-hook -g session-created \"run-shell '%s bar-adjust'\"\n", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g session-closed \"run-shell '%s bar-adjust'\"\n", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g client-session-changed[1] \"run-shell '%s bar-adjust'\"\n", zmuxBin)
	}
	b.WriteString("\n")

	// Bootstrap: apply theme + bar on tmux start
	writeSection(&b, "Bootstrap")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "run-shell \"%s apply --bootstrap\"\n", zmuxBin)
	}

	return b.String()
}

// WriteConf writes the generated config content to the given path,
// creating parent directories as needed.
func WriteConf(fs config.FS, path, content string) error {
	dir := filepath.Dir(path)
	if err := fs.MkdirAll(dir, os.FileMode(0o755)); err != nil {
		return fmt.Errorf("create config dir %q: %w", dir, err)
	}
	if err := fs.WriteFile(path, []byte(content), os.FileMode(0o644)); err != nil {
		return fmt.Errorf("write config %q: %w", path, err)
	}
	return nil
}

func writeSection(b *strings.Builder, name string) {
	fmt.Fprintf(b, "# --- %s ---\n", name)
}
