package tmux

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donjor/zmux/internal/config"
	"github.com/donjor/zmux/internal/keys"
	"github.com/donjor/zmux/internal/tablabel"
	"github.com/donjor/zmux/internal/termtitle"
	"github.com/donjor/zmux/internal/theme"
)

// GenerateConf produces a tmux configuration string from the given config and palette.
// zmuxBin is the path to the zmux binary for run-shell commands.
func GenerateConf(cfg *config.Config, palette *theme.Palette, zmuxBin string) string {
	var b strings.Builder

	// Header
	b.WriteString("# Generated by zmux — do not edit manually\n")
	b.WriteString("# https://github.com/donjor/zmux\n\n")

	// General settings
	writeSection(&b, "General")
	b.WriteString("set -g default-terminal \"tmux-256color\"\n")
	b.WriteString("set -g extended-keys on\n")
	b.WriteString("# zmux owns terminal-features[90..99] to keep repeated apply idempotent.\n")
	b.WriteString("set -g terminal-features[90] \"xterm-256color:RGB:extkeys\"\n")
	b.WriteString("set -g terminal-features[91] \"xterm-ghostty:RGB:extkeys\"\n")
	b.WriteString("set -g terminal-features[92] \"tmux-256color:RGB:extkeys\"\n")
	b.WriteString("set -g mouse on\n")
	b.WriteString("set -g history-limit 50000\n")
	b.WriteString("set -g escape-time 50\n")
	// 500ms (tmux's own default) over a tighter 300: the prefix+Arrow resize
	// binds are repeatable (-r), but a 300ms window closes before a human can
	// press the arrow again, so resize felt one-shot ("the prefix gets
	// consumed"). 500ms lets consecutive resize/reorder/session-nav presses
	// chain without re-pressing the prefix.
	b.WriteString("set -g repeat-time 500\n")
	b.WriteString("set -g focus-events on\n")
	b.WriteString("set -g base-index 1\n")
	b.WriteString("setw -g pane-base-index 1\n")
	b.WriteString("set -g renumber-windows on\n")
	// Use tmux's normal command-based auto naming. zmux marks duplicate names
	// separately so the status bar can add a cwd suffix only when needed.
	b.WriteString("setw -g automatic-rename on\n")
	b.WriteString("setw -g automatic-rename-format \"#{?pane_in_mode,[tmux],#{pane_current_command}}\"\n")
	// Keep the tab visible when its last foreground command exits by failure or
	// signal (for example Ctrl+C spam killing a full-tab Pi session). Clean status
	// 0 exits close normally instead of leaving a confusing dead pane.
	b.WriteString("setw -g remain-on-exit failed\n")
	b.WriteString("setw -g remain-on-exit-format \"Pane stopped unexpectedly#{?#{!=:#{pane_dead_status},}, (status #{pane_dead_status}),}#{?#{!=:#{pane_dead_signal},}, (signal #{pane_dead_signal}),} — press prefix+x to close the tab\"\n")
	b.WriteString("set -g set-clipboard on\n")
	b.WriteString("set -g status-position top\n")
	b.WriteString("set -g set-titles on\n")
	fmt.Fprintf(&b, "set -g set-titles-string \"%s\"\n", termtitle.TmuxTitleFormat)
	// Idle baseline — also the #() cache TTL for bar-render. While any pane
	// holds a running tab state, tabstate.Service drops this to 1s so the
	// #(bar-spinner) glyph steps, and restores 5s when the last one clears
	// (no constant 1s bar-render spawn load while nothing runs).
	b.WriteString("set -g status-interval 5\n")
	b.WriteString("set -g status-left-length 40\n")
	b.WriteString("set -g status-right-length 100\n")
	// Rounded popup chrome for dashboard, pickers, scratch — quieter framing.
	b.WriteString("set -g popup-border-lines rounded\n")
	// Faint border in the theme's dim color, so a popup reads as a layer
	// floating above the host rather than another framed pane. Always-on and
	// regenerated on theme change (apply re-runs GenerateConf).
	if palette != nil {
		fmt.Fprintf(&b, "set -g popup-border-style fg=%s\n", palette.Dim.Hex())
	}
	b.WriteString("\n")

	// Prefix
	prefix := cfg.Prefix
	if prefix == "" {
		prefix = "C-Space"
	}
	writeSection(&b, "Prefix")
	b.WriteString("unbind C-b\n")
	fmt.Fprintf(&b, "set -g prefix %s\n", prefix)
	fmt.Fprintf(&b, "bind %s send-prefix\n", prefix)
	b.WriteString("\n")

	// Vim copy mode
	writeSection(&b, "Vim copy mode")
	b.WriteString("setw -g mode-keys vi\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "bind %s copy-mode\n", keys.CopyModeKey.Key)
	fmt.Fprintf(&b, "bind %s respawn-pane -k\n", keys.PaneRespawn.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X begin-selection\n", keys.CopyBeginSelection.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X cancel\n", keys.CopyCancel.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s send -X rectangle-toggle\n", keys.CopyRectangle.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s command-prompt -p \"search down:\" \"send -X search-forward '%%%%'\"\n", keys.CopySearchForward.Key)
	fmt.Fprintf(&b, "bind -T copy-mode-vi %s command-prompt -p \"search up:\" \"send -X search-backward '%%%%'\"\n", keys.CopySearchBackward.Key)
	b.WriteString("\n")

	// Clipboard
	clipTool := DetectClipboard()
	b.WriteString("# Clipboard\n")
	b.WriteString(ClipboardBinding(clipTool))
	b.WriteString("\n\n")

	// Windows (tabs)
	writeSection(&b, "Windows")
	fmt.Fprintf(&b, "bind %s new-window -c \"#{pane_current_path}\"\n", keys.NewTab.Key)
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s run-shell \"%s tab split --notify\"\n", keys.TabSplit.Key, zmuxBin)
	}
	fmt.Fprintf(&b, "bind %s next-window\n", keys.TabNext.Key)
	fmt.Fprintf(&b, "bind %s previous-window\n", keys.TabPrev.Key)
	fmt.Fprintf(&b, "bind %s command-prompt -p \"label tab (blank clears):\" \"set-option -w -t #{window_id} @zmux_label '%%%%' \\; set-option -w -t #{window_id} @zmux_label_source manual\"\n", keys.LabelTab.Key)
	fmt.Fprintf(&b, "bind %s swap-window -t -1 \\; select-window -t -1\n", keys.TabReorderLeft.Key)
	fmt.Fprintf(&b, "bind %s swap-window -t +1 \\; select-window -t +1\n", keys.TabReorderRight.Key)
	fmt.Fprintf(&b, "bind %s confirm-before -p \"close tab %s? (y/n)\" kill-window\n", keys.TabKill.Key, tablabel.PlainFormat())
	if zmuxBin != "" {
		// --notify routes the outcome to a transient status-line message and
		// exits 0, so a failed/loud join or promote never triggers tmux's
		// view-mode takeover ("... returned 1" / a sticky stdout dump) that the
		// user must keypress away.
		fmt.Fprintf(&b, "bind %s command-prompt -p \"join tab here:\" \"run-shell '%s tab pane --notify \\\"%%%%\\\"'\"\n", keys.TabJoinPane.Key, zmuxBin)
		fmt.Fprintf(&b, "bind %s run-shell \"%s tab full --after --notify\"\n", keys.TabFull.Key, zmuxBin)
	}
	b.WriteString("\n")

	// Mouse pane menu. Header drag-swap stays deferred: tmux 3.4 exposes pane
	// headers through generic Pane/Border locations, and MouseDrag1Border is
	// the native resize path. This menu-only fallback binds the pane body and
	// leaves border resize untouched.
	if zmuxBin != "" {
		writeSection(&b, "Mouse pane menu")
		fmt.Fprintf(&b, "bind -T root MouseDown3Pane display-menu -T \"Pane #{pane_index}\" -t \"#{mouse_pane}\" -x M -y M \"Promote to full\" f { select-pane -t \"#{mouse_pane}\" ; run-shell \"%s tab full --pane \\\"#{mouse_pane}\\\" --after --notify\" } \"Hide to dock\" h { select-pane -t \"#{mouse_pane}\" ; run-shell \"%s tab hide --pane \\\"#{mouse_pane}\\\" --notify\" } \"Kill pane\" x { select-pane -t \"#{mouse_pane}\" ; kill-pane }\n", zmuxBin, zmuxBin)
		b.WriteString("\n")
	}

	// Alt+1-9 tab switching (no prefix)
	b.WriteString("# Alt+1-9 tab switching (no prefix)\n")
	for i := 1; i <= 9; i++ {
		fmt.Fprintf(&b, "bind -n M-%d select-window -t %d\n", i, i)
	}
	b.WriteString("\n")

	// Alt+` tab switcher for current session (no prefix)
	if zmuxBin != "" {
		popupBind(&b, true, keys.TabSwitch.Key, 60, 40, zmuxBin, "--tab-picker")
		// Alt+w workspace switcher (no prefix). Parallels Alt+`.
		// Caveat: shadows Emacs/readline Meta-w (copy-region) inside inner shells.
		popupBind(&b, true, keys.WorkspaceSwitch.Key, 50, 50, zmuxBin, "--workspace-picker")
	}
	b.WriteString("\n")

	// No-prefix pane focus. Alt+Shift+Arrow avoids stealing plain Alt+Arrow
	// from shells and TUIs. Large pane resize remains prefix+Alt+Arrow in
	// tmux's prefix table, so the chords stay separate.
	b.WriteString("# Alt+Shift+Arrow pane focus (no prefix)\n")
	b.WriteString("unbind -n M-Left\n")
	b.WriteString("unbind -n M-Right\n")
	b.WriteString("unbind -n M-Up\n")
	b.WriteString("unbind -n M-Down\n")
	b.WriteString("unbind -n M-S-Left\n")
	b.WriteString("unbind -n M-S-Right\n")
	b.WriteString("unbind -n M-S-Up\n")
	b.WriteString("unbind -n M-S-Down\n")
	fmt.Fprintf(&b, "bind -n %s select-pane -L\n", keys.PaneFocusL.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -R\n", keys.PaneFocusR.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -U\n", keys.PaneFocusU.Key)
	fmt.Fprintf(&b, "bind -n %s select-pane -D\n", keys.PaneFocusD.Key)
	b.WriteString("\n")

	// Pane layout (prefix). Swap the active pane with the neighbor in a
	// direction (-r repeatable, so a pane can be walked across the layout — focus
	// follows the moved pane), equalize splits, and toggle split orientation.
	// The orient toggle flips even-horizontal <-> even-vertical by inspecting
	// window_layout (a left-right split nests as `{...}`); nested/multi-pane
	// layouts flatten to an even spread — the documented v1 ceiling.
	writeSection(&b, "Pane layout")
	fmt.Fprintf(&b, "bind -r %s swap-pane -t '{left-of}'\n", keys.PaneSwapLeft.Key)
	fmt.Fprintf(&b, "bind -r %s swap-pane -t '{right-of}'\n", keys.PaneSwapRight.Key)
	fmt.Fprintf(&b, "bind -r %s swap-pane -t '{up-of}'\n", keys.PaneSwapUp.Key)
	fmt.Fprintf(&b, "bind -r %s swap-pane -t '{down-of}'\n", keys.PaneSwapDown.Key)
	fmt.Fprintf(&b, "bind %s select-layout -E\n", keys.PaneEqualize.Key)
	fmt.Fprintf(&b, "bind %s if -F \"%s\" \"select-layout %s\" \"select-layout %s\"\n", keys.SplitOrient.Key, OrientHorizontalMatch, LayoutEvenVertical, LayoutEvenHorizontal)
	b.WriteString("\n")

	// Sessions
	writeSection(&b, "Sessions")
	fmt.Fprintf(&b, "bind %s command-prompt -p \"rename session:\" \"rename-session '%%%%'\"\n", keys.RenameSession.Key)
	if zmuxBin != "" {
		// prefix+C (shift-c): create new session in current workspace.
		fmt.Fprintf(&b, "bind %s command-prompt -p \"new session:\" \"run-shell '%s workspace new-session %%%%'\"\n", keys.NewSession.Key, zmuxBin)
	}
	b.WriteString("\n")

	// Session navigation (workspace-scoped)
	writeSection(&b, "Session navigation")
	if zmuxBin != "" {
		// prefix+w: hierarchical workspace+session picker. (prefix+s was a
		// second alias here; it's been reclaimed for the pane split-orientation
		// toggle above — pane-mode keys take priority over a redundant picker
		// alias. Any remaining SessionPicker.Aliases still bind.)
		for _, k := range append([]string{keys.SessionPicker.Key}, keys.SessionPicker.Aliases...) {
			popupBind(&b, false, k, 60, 50, zmuxBin, "--picker")
		}
		// prefix+Alt+1-9: direct session switching in the current workspace.
		// Keeping the digit jumps behind prefix avoids stealing Alt+digits from
		// shells/editors while preserving the tab/session parallel:
		// Alt+N = tab N, prefix+Alt+N = session N.
		for i := 1; i <= 9; i++ {
			fmt.Fprintf(&b, "bind M-%d run-shell \"%s workspace switch-to %d\"\n", i, zmuxBin, i)
		}
		// prefix+[ / prefix+]: cycle prev/next session in workspace
		fmt.Fprintf(&b, "bind %s run-shell \"%s workspace prev\"\n", keys.SessionPrev.Key, zmuxBin)
		fmt.Fprintf(&b, "bind %s run-shell \"%s workspace next\"\n", keys.SessionNext.Key, zmuxBin)
	} else {
		// No zmux binary: fall back to tmux's native session tree on prefix+w
		// (prefix+s is now the pane orient toggle, matching the binary path).
		b.WriteString("bind w choose-tree -s\n")
	}
	b.WriteString("\n")

	// Pasting
	writeSection(&b, "Pasting")
	fmt.Fprintf(&b, "bind %s paste-buffer\n", keys.Paste.Key)
	b.WriteString("\n")

	// Command Palette popup (prefix+p)
	writeSection(&b, "Command Palette")
	if zmuxBin != "" {
		popupBind(&b, false, keys.Palette.Key, 60, 50, zmuxBin, "--palette")
	}
	b.WriteString("\n")

	// Dashboard popup (prefix+Space — "double-tap" zmux)
	writeSection(&b, "Dashboard")
	if zmuxBin != "" {
		popupBind(&b, false, keys.Dashboard.Key, 80, 80, zmuxBin, "--dashboard")
	}
	b.WriteString("\n")

	// Help popup (prefix+?) — interactive scrollable + fuzzy-filterable viewer.
	b.WriteString("# Help\n")
	if zmuxBin != "" {
		popupBind(&b, false, keys.Help.Key, 70, 80, zmuxBin, "--help-menu")
	}
	b.WriteString("\n")

	// Scratch shell popup (prefix+!) — throwaway $SHELL in a popup, cwd
	// inherits from the calling pane, closes on exit. Run `<bin> scratch
	// extract` from inside to promote the cwd into a real tab. The title
	// advertises the active profile's binary (zmux | zzmux) so following the
	// hint never crosses profiles — under zzmux, `zmux scratch extract` would
	// silently act on the wrong server.
	writeSection(&b, "Scratch shell")
	scratchBin := "zmux"
	if zmuxBin != "" {
		scratchBin = filepath.Base(zmuxBin)
	}
	fmt.Fprintf(&b, "bind %s display-popup -E -w 80%% -h 70%% -T \" scratch · %s scratch extract → tab \" -d \"#{pane_current_path}\" \"$SHELL\"\n", keys.ScratchShell.Key, scratchBin)
	b.WriteString("\n")

	// Reload (prefix+r runs full zmux apply — regenerates conf + applies everything)
	writeSection(&b, "Reload")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "bind %s run-shell \"%s apply\" \\; display \"zmux reloaded\"\n", keys.Reload.Key, zmuxBin)
	} else {
		fmt.Fprintf(&b, "bind %s source-file ~/.tmux.conf \\; display \"Config reloaded\"\n", keys.Reload.Key)
	}
	b.WriteString("\n")

	// Status bar refresh hooks — force immediate refresh on context change
	// so the bar doesn't show stale session/window info for 5 seconds.
	//
	// Each refresh is guarded by `if-shell -F '#{client_tty}'`: bare
	// `refresh-client -S` errors "(null):0: no current client" when a hook
	// fires with no client to refresh — e.g. a zmux CLI command run from a
	// shell that isn't attached to any session triggers session-created/closed.
	// Gating on the hook's current client tty (empty ⟹ tmux has no client
	// here) skips the refresh silently in that case while still firing it when
	// a client is present. client_tty over session_attached because the latter
	// would gate session-closed on the dying session's attach count (always 0)
	// and wrongly skip a refresh another client still wants.
	writeSection(&b, "Status refresh hooks")
	const refresh = "if-shell -F '#{client_tty}' 'refresh-client -S'"
	fmt.Fprintf(&b, "set-hook -g client-session-changed \"%s\"\n", refresh)
	fmt.Fprintf(&b, "set-hook -g session-window-changed \"%s\"\n", refresh)
	fmt.Fprintf(&b, "set-hook -g window-linked \"%s\"\n", refresh)
	fmt.Fprintf(&b, "set-hook -g window-renamed \"%s\"\n", refresh)
	fmt.Fprintf(&b, "set-hook -g session-renamed \"%s\"\n", refresh)
	// session-created/closed share an index 0 slot with bar-adjust below, so
	// the refresh lives at index [2] to keep both concerns visible.
	fmt.Fprintf(&b, "set-hook -g session-created[2] \"%s\"\n", refresh)
	fmt.Fprintf(&b, "set-hook -g session-closed[2] \"%s\"\n", refresh)
	if zmuxBin != "" {
		// Clear older generated hook slots before installing the current silent,
		// best-effort hooks. In particular, a legacy unindexed window-unlinked hook
		// could surface noisy "returned 1" messages from old binaries.
		b.WriteString("set-hook -gu window-unlinked[0]\n")
		b.WriteString("set-hook -gu window-linked[1]\n")
		b.WriteString("set-hook -gu window-unlinked[1]\n")
		b.WriteString("set-hook -gu window-renamed[1]\n")
		b.WriteString("set-hook -gu window-linked[2]\n")
		refreshNamesCmd := fmt.Sprintf("%s tab refresh-names #{session_name} >/dev/null 2>&1 || true", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g window-linked[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
		fmt.Fprintf(&b, "set-hook -g window-unlinked[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
		fmt.Fprintf(&b, "set-hook -g window-renamed[1] \"run-shell -b '%s'\"\n", refreshNamesCmd)
		// Stamp a window born interactively (prefix+c / new-window) as a managed
		// tab so index/name addressing and `tab pane` joins accept it — the
		// symmetric completion of session.Create's first-window stamp.
		// #{hook_window} is the precise newly-linked window (not the session's
		// active window, which differs under new-window -d / link-window).
		adoptCmd := fmt.Sprintf("%s tab adopt #{hook_window} >/dev/null 2>&1 || true", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g window-linked[2] \"run-shell -b '%s'\"\n", adoptCmd)

		// Focus clears `attention` (ratified clear table; done/failed stay
		// until input). session-window-changed covers switching tabs;
		// window-pane-changed covers switching panes within a tab. Both fire
		// reliably without focus-events — pane-focus-in does not (spike C,
		// plan 026), so it is deliberately absent here. #{pane_id} expands to
		// the newly-active pane when the hook fires.
		focusClearCmd := fmt.Sprintf("%s tab state clear --target #{pane_id} --if attention --source focus --quiet >/dev/null 2>&1 || true", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g session-window-changed[1] \"run-shell -b '%s'\"\n", focusClearCmd)
		fmt.Fprintf(&b, "set-hook -g window-pane-changed \"run-shell -b '%s'\"\n", focusClearCmd)

		// Baked-in tab reaper (plan 038). Lazy + throttled sweep on the
		// low-frequency, non-recursive lifecycle events: a human sitting down
		// (client-attached) and a new session being born (session-created, e.g. an
		// agent's `session run`). The reaper kills windows, never creates sessions
		// or attaches, so neither event re-fires from a sweep; the @zmux_last_reap
		// throttle dedupes bursts. Backgrounded (-b), silent, best-effort.
		reapCmd := fmt.Sprintf("%s reap --lazy --quiet >/dev/null 2>&1 || true", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g client-attached[1] \"run-shell -b '%s'\"\n", reapCmd)
		fmt.Fprintf(&b, "set-hook -g session-created[3] \"run-shell -b '%s'\"\n", reapCmd)
	}

	// Two-line bar hooks — reconcile per-session status lines to the configured
	// layout (always-2-line for two-line/split; no count-based collapse, so the
	// bar never reflows). No -b flag: run synchronously so the status count is
	// correct before redraw.
	if zmuxBin != "" {
		// Explicit [0] index, NOT a bare name. An unindexed `set-hook -g
		// session-created` REPLACES the whole hook array, wiping the indexed
		// refresh[2] and reaper[3] hooks set above (verified: tmux clobbers the
		// array on an unindexed write). Pinning bar-adjust to its [0] slot keeps
		// all three live.
		fmt.Fprintf(&b, "set-hook -g session-created[0] \"run-shell '%s bar-adjust'\"\n", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g session-closed[0] \"run-shell '%s bar-adjust'\"\n", zmuxBin)
		fmt.Fprintf(&b, "set-hook -g client-session-changed[1] \"run-shell '%s bar-adjust'\"\n", zmuxBin)
	}
	b.WriteString("\n")

	// Bootstrap: apply theme + bar on tmux start
	writeSection(&b, "Bootstrap")
	if zmuxBin != "" {
		fmt.Fprintf(&b, "run-shell \"%s apply --bootstrap\"\n", zmuxBin)
	}

	return b.String()
}

// WriteConf writes the generated config content to the given path,
// creating parent directories as needed.
func WriteConf(fs config.FS, path, content string) error {
	dir := filepath.Dir(path)
	if err := fs.MkdirAll(dir, os.FileMode(0o755)); err != nil {
		return fmt.Errorf("create config dir %q: %w", dir, err)
	}
	if err := fs.WriteFile(path, []byte(content), os.FileMode(0o644)); err != nil {
		return fmt.Errorf("write config %q: %w", path, err)
	}
	return nil
}

func writeSection(b *strings.Builder, name string) {
	fmt.Fprintf(b, "# --- %s ---\n", name)
}

// popupBind writes a `display-popup` keybind that re-invokes the zmux binary
// (selfBin) with the given args. noPrefix emits a root-table (-n) bind; the
// default is a prefix-table bind. Callers guard on selfBin != "", so a missing
// binary path omits the bind entirely rather than falling back to a hardcoded
// "zmux" — which would break profile isolation for the zzmux edge binary.
func popupBind(b *strings.Builder, noPrefix bool, key string, w, h int, selfBin, args string) {
	table := ""
	if noPrefix {
		table = "-n "
	}
	fmt.Fprintf(b, "bind %s%s display-popup -w %d%% -h %d%% -E \"%s %s\"\n", table, key, w, h, selfBin, args)
}
